// <auto-generated />
namespace Onion.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EXPENSE_NUMBERComputed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EXPENSE_NUMBERComputed));
        
        string IMigrationMetadata.Id
        {
            get { return "202004091059295_EXPENSE_NUMBERComputed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
