// <auto-generated />
namespace Onion.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TravelExpenseT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TravelExpenseT));
        
        string IMigrationMetadata.Id
        {
            get { return "202004140630411_TravelExpenseT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
